# Generated by Django 3.1.4 on 2020-12-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_obj', models.JSONField(default=dict)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.IntegerField(default=2020)),
                ('imdbID', models.CharField(max_length=10, unique=True)),
                ('poster', models.ImageField(upload_to='')),
                ('rated', models.CharField(max_length=10)),
                ('released', models.CharField(max_length=50)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('awards', models.CharField(max_length=200)),
                ('imdbRating', models.FloatField()),
                ('imdbVotes', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('production', models.CharField(max_length=200)),
            ],
        ),
    ]
